### PR TITLE
Falcon500 going the distance

### PR DESCRIPTION
**Pull request by ManiacMoustache**
Adds a new state machine and component for control of the drivetrain. Use setDistance() to give it a distance.

### CODE REVIEW

**Comment by ManiacMoustache** [comment]
He's going for speed

**Comment by ManiacMoustache** [comment]
She's all alone (all alone)

**Comment by ManiacMoustache** [comment]
All alone in her time of need

**Review by ChrisHirsch — APPROVED** [review]
+1

**Pull request merged**
